<?xml version="1.0"?>
<robot name="$(arg robot_ns)" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="robot_ns" default="robot1"/>

  <!-- ========= PARAMÈTRES ========= -->
  <xacro:property name="base_length" value="0.2"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="wheel_radius" value="0.162"/>
  <xacro:property name="wheel_width" value="0.150"/>
  <xacro:property name="wheel_y" value="0.317"/>
  <xacro:property name="wheel_x" value="-0.15"/>
  <xacro:property name="wheel_z" value="${wheel_radius}"/>
  <xacro:property name="caster_radius" value="0.13"/>
  <xacro:property name="caster_width" value="0.08"/>
  <xacro:property name="caster_dx" value="-0.747"/>
  <xacro:property name="caster_dy" value="0.26"/>
  <xacro:property name="caster_plate_size" value="0.18"/>
  <xacro:property name="caster_plate_th" value="0.01"/>
  <xacro:property name="caster_z" value="${caster_radius + caster_plate_th/2}"/>
  <xacro:property name="sensor_radius" value="0.04"/>
  <xacro:property name="sensor_height" value="0.06"/>

  <!-- ========= MATÉRIAUX ========= -->
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="bleu"><color rgba="0 0 1 1"/></material>
  <material name="jaune"><color rgba="1 1 0 1"/></material>

  <!-- ========= FOOTPRINT ========= -->
  <link name="base_footprint"/>

  <!-- ========= BASE LINK ========= -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="-0.025 0 0"/>
      <material name="bleu"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="-0.025 0 0"/>
    </collision>
    <inertial>
      <mass value="50.0"/>
      <origin xyz="-0.2 0 0.1"/>
      <inertia ixx="0.76" ixy="0" ixz="0" iyy="0.26" iyz="0" izz="0.833"/>
    </inertial>

    <!-- Grande plaque -->
    <visual>
      <geometry>
        <box size="0.7 0.8 0.02"/>
      </geometry>
      <origin xyz="-0.5 0 ${caster_radius * 2 + caster_plate_th / 2 - wheel_radius + 0.02}"/>
      <material name="bleu"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.7 0.8 0.02"/>
      </geometry>
      <origin xyz="-0.5 0 ${caster_radius * 2 + caster_plate_th / 2 - wheel_radius + 0.02}"/>
    </collision>

    <!-- Boite -->
    <visual>
      <geometry>
        <box size="0.8 0.8 0.7"/>
      </geometry>
      <origin xyz="-0.55 0 0.5"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.8 0.8 0.7"/>
      </geometry>
      <origin xyz="-0.55 0 0.5"/>
    </collision>

    <!-- Plaque avant -->
    <visual>
      <geometry>
        <box size="0.9 ${base_width} ${base_height - 0.1}"/>
      </geometry>
      <origin xyz="-0.05 0 0.5" rpy="0 1.4 0"/>
      <material name="bleu"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.9 ${base_width} ${base_height - 0.1}"/>
      </geometry>
      <origin xyz="-0.05 0 0.5" rpy="0 1.4 0"/>
    </collision>
  </link>

  <joint name="base_link_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_z}"/>
  </joint>

  <!-- ========= MACRO ROUE MOTRICE ========= -->
  <xacro:macro name="drive_wheel" params="name sign">
    <link name="${name}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570796 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570796 0 0"/>
        <surface>
          <friction>
            <ode>
              <mu>1.0</mu>
              <mu2>1.0</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <inertial>
        <mass value="8.0"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0"
                 iyy="0.06" iyz="0.0"
                 izz="0.06"/>
      </inertial>
    </link>
    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_wheel_link"/>
      <origin xyz="0 ${sign * wheel_y} 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="50000" velocity="10"/>
      <dynamics damping="1.0" friction="1.0"/>
    </joint>
  </xacro:macro>

  <xacro:drive_wheel name="left"  sign=" 1"/>
  <xacro:drive_wheel name="right" sign="-1"/>

  <!-- ========= MACRO MODULE ROULETTE ========= -->
  <xacro:macro name="caster" params="side sign">
    <link name="${side}_caster_plate_link">
      <visual>
        <geometry>
          <box size="${caster_plate_size} ${caster_plate_size} ${caster_plate_th}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <geometry>
          <box size="${caster_plate_size} ${caster_plate_size} ${caster_plate_th}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0"
                 izz="0.002"/>
      </inertial>
    </link>
    <joint name="${side}_caster_plate_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${side}_caster_plate_link"/>
      <origin xyz="${caster_dx} ${sign * caster_dy} ${caster_radius * 2 + caster_plate_th / 2 - wheel_radius}"/>
      <axis xyz="0 0 1"/>
    </joint>
    <!-- petite roue -->
    <link name="${side}_caster_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570796 0 0"/>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${caster_radius}" length="${caster_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570796 0 0"/>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0037" ixy="0.0" ixz="0.0"
                 iyy="0.0037" iyz="0.0"
                 izz="0.0010"/>
      </inertial>
    </link>
    <joint name="${side}_caster_wheel_joint" type="continuous">
      <parent link="${side}_caster_plate_link"/>
      <child link="${side}_caster_wheel_link"/>
      <origin xyz="-0.06 0 -${caster_radius}"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:caster side="left"  sign=" 1"/>
  <xacro:caster side="right" sign="-1"/>

  <!-- ========= MACRO CAPTEUR CYLINDRE AVEC ORIENTATION ========= -->
  <xacro:macro name="lidar_sensor" params="name origin_x origin_y origin_z origin_rpy">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${sensor_radius}" length="${sensor_height}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${sensor_radius}" length="${sensor_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="${origin_rpy}"/>
    </joint>
  </xacro:macro>

  <!-- ========= INSTANCES CAPTEURS ========= -->
  <xacro:lidar_sensor name="airy_front"   origin_x="0.05"  origin_y="0.0" origin_z="0.8" origin_rpy="0 2.0 0"/>
  <xacro:lidar_sensor name="jt16_center"  origin_x="-0.607" origin_y="0.0" origin_z="0.025" origin_rpy="0 3.14 0"/>
  <xacro:lidar_sensor name="airy_back"    origin_x="-0.870" origin_y="0.0" origin_z="0.085" origin_rpy="0 -1.57 0"/>

  <xacro:include filename="$(find hive_robot_description)/model/mk5_200.gazebo"/>
  <xacro:add_gazebo_tags robot_ns="$(arg robot_ns)"/>

</robot>
